import { escapeHtml as e } from './html.js';
import { icon as i } from './icons.js';
import { renderAdSlot } from './ads.js';
import { posts, people, news } from './data.js';
import { currentUser } from '@larpedin/shared';
import { renderFooter } from './footer.js';
import { showNewsSource } from './flags.js';
export const avatar = (name, size = '', alt = '') => `<span class="avatar avatar-${e(name)} ${size}" ${alt ? `role="img" aria-label="${e(alt)}"` : 'aria-hidden="true"'}></span>`;
const btn = (action, text, glyph, cls = '') => `<button type="button" class="${cls}" data-action="${action}">${glyph ? i(glyph) : ''}${text}</button>`;
export function renderPost(post, index = 0) {
 const imageSource=typeof post.image==='string'?post.image:post.image?'/assets/morning.webp':undefined;
 const imageAlt=post.imageAlt || 'A founder’s untouched laptop and morning coffee overlooking a garden';
 return `<article class="card post" id="${e(post.id)}" data-post="${e(post.id)}" data-category="${e(post.tag)}" data-likes="${post.likes}" data-index="${index}">
 <div class="post-context">${i('users-three')}<span>${e(post.social || 'Fresh from your keyboard')}</span><button class="icon-button post-save" data-action="save" aria-label="Save post" aria-pressed="false">${i('bookmark-simple')}</button><button class="icon-button" data-action="hide" aria-label="Hide post">${i('x')}</button></div>
 <div class="post-author">${avatar(post.avatar)}<div class="author-copy"><strong>${e(post.name)} ${i('seal-check',true)} <span>· 2nd</span></strong><p>${e(post.role)}</p><small>${e(post.time)} · ${i('globe-hemisphere-west')}</small></div><button class="follow" data-action="follow" aria-pressed="false">${i('plus')} Follow</button></div>
 <div class="post-body">${post.body.map(p=>`<p>${e(p)}</p>`).join('')}${post.more ? `<details class="post-more"><summary>…more</summary><p>${e(post.more)}</p></details>` : ''}<p class="hashtags">${e(post.tags || '')}</p></div>
 ${imageSource?`<img class="post-photo" src="${e(imageSource)}" width="900" height="600" loading="lazy" decoding="async" alt="${e(imageAlt)}">`:''}
 ${post.sourceUrl && showNewsSource() ? `<div class="post-source"><a href="${e(post.sourceUrl)}" target="_blank" rel="noopener noreferrer">Read full story here <span aria-hidden="true">↗</span></a></div>` : ''}
 <div class="post-stats"><span class="reactions" aria-hidden="true"><b>${i('thumbs-up',true)}</b><b>${i('hands-clapping',true)}</b><b>${i('heart',true)}</b></span><span data-like-count>${post.likes.toLocaleString('en-GB')}</span><button data-action="comment" class="comment-count">${post.comments} comments</button><span>${post.reposts} reposts</span></div>
 <div class="post-actions">${btn('like','Like','thumbs-up')}${btn('comment','Comment','chat-circle-text')}${btn('repost','Repost','arrows-clockwise')}${btn('share','Send','paper-plane-tilt')}</div>
 <section class="comments" hidden aria-label="Comments"><form class="comment-form"><label class="sr-only" for="comment-${e(post.id)}">Write a comment</label><input id="comment-${e(post.id)}" name="comment" placeholder="Add to the discourse…" maxlength="500" required><button class="button primary" type="submit">Post</button></form><ul class="comment-list"></ul><p class="muted small">Your comments stay in this browser. Your wisdom is safe here.</p></section>
 ${renderAdSlot({postId:post.id,index})}</article>`;
}
function leftRail(){return `<aside class="left-rail" aria-label="Your profile"><section class="card profile-card"><div class="profile-cover"></div>${avatar('you','profile-avatar')}<div class="profile-text"><h1>${e(currentUser.name)} ${i('seal-check',true)}</h1><p>CEO of ${e(currentUser.company)}.<br>${e(currentUser.tagline)}</p><small>${e(currentUser.location)}</small><strong class="company">${i('buildings')} 2,347,891 followers (allegedly)</strong></div></section>
 <section class="card profile-stats"><button data-action="profile"><span>Profile viewers</span><b>128</b></button><button data-action="profile"><span>Post impressions</span><b>2,048</b></button><p>All the metrics. None of the meaning.</p></section>
 <section class="card premium"><small>Make your humblebrags work harder</small><button data-action="premium"><span class="premium-square"></span> Try Premium Delusion</button></section>
 <nav class="card shortcuts" aria-label="Your shortcuts">${btn('saved','Saved posts','bookmark-simple','shortcut')}${btn('groups','Echo chambers','users-three','shortcut')}${btn('newsletter','Newsletters nobody asked for','newspaper','shortcut')}${btn('events','Events','calendar-blank','shortcut')}</nav>
 <div class="parody-note"><span class="wordmark"><img src="/larpedin-bubble.svg" alt="">LarpedIn</span><p>Genuine news.<br>Satirical takes.</p><small>An independent parody. Not affiliated<br>with LinkedIn or any featured company.</small></div></aside>`;}
function renderHeadlines(headlines){return headlines.map(h=>`<li>${h.url?`<a href="${e(h.url)}" target="_blank" rel="noopener noreferrer">`:'<div>'}<strong>${e(h.title)}</strong><small>${e(h.time||'Recently')}${h.url?`<span> · ${e(h.author||h.sourceName||'')}</span>`:''}</small>${h.url?'</a>':'</div>'}</li>`).join('');}
function rightRail(feed){return `<aside class="right-rail" aria-label="News and recommendations"><section class="card news"><div class="section-title"><h2>LarpedIn News</h2>${btn('about','', 'info','icon-button')}</div><p class="muted news-subtitle">${feed?(feed.sourceName?`Latest from ${e(feed.sourceName)} · Refreshed hourly`:'Latest technology news · Refreshed hourly'):'Loading the latest technology news…'}</p><ul id="latest-news">${feed?renderHeadlines(feed.headlines):news.map((n,k)=>`<li><button data-action="news" data-news="${k}"><strong>${n[0]}</strong><small>${n[1]} <span>· ${n[2]}</span></small></button></li>`).join('')}</ul>${showNewsSource()?`<a class="text-button news-more" href="https://techcrunch.com/" target="_blank" rel="noopener noreferrer">More technology news <span aria-hidden="true">↗</span></a>`:''}<div class="puzzle"><div class="puzzle-icon">${i('puzzle-piece',true)}</div><div><strong>Daily Buzzword Bingo</strong><p>A little game. A lot of synergy.</p></div><button data-action="bingo" class="icon-button" aria-label="Play Buzzword Bingo">${i('caret-right')}</button></div></section>
 <section class="card suggestions"><h2>Add to your echo chamber</h2>${people.map(p=>`<div class="suggestion">${avatar(p.avatar)}<div><strong>${p.name}</strong><p>${p.role}</p><button class="button outline" data-action="follow" aria-pressed="false">${i('plus')} Follow</button></div></div>`).join('')}<button class="text-button" data-action="network">View all recommendations ${i('arrow-right')}</button></section>
 <section class="card sidebar-ad"><div class="sidebar-ad-label">Advertisement ${i('dots-three')}</div><div class="coffee-icon">${i('coffee')}</div><h3>Buy us a coffee.<br>We’ll call it a seed round.</h3><p>Support independent, vertically<br>integrated nonsense.</p><button class="button outline" data-action="sponsor">Become a founding drinker</button></section>
 ${renderFooter()}</aside>`;}
export function renderPage(feed){const feedPosts=feed?feed.posts:posts;return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0a66c2"><title>LarpedIn | Genuine news. Satirical takes.</title><meta name="description" content="The professional network for confidently incorrect tech takes. A light-hearted, independent LinkedIn parody."><meta property="og:title" content="LarpedIn: All the confidence. None of the qualifications."><meta property="og:description" content="Your daily dose of thought leadership, founder wisdom and completely unearned confidence."><link rel="icon" href="/larpedin-bubble.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script type="module" src="/app.js"></script></head><body><a href="#feed" class="skip-link">Skip to feed</a>
 <header class="topbar"><div class="nav-inner"><a href="/" class="wordmark" aria-label="LarpedIn home"><img src="/larpedin-bubble.svg" alt="">LarpedIn</a><form class="search" role="search"><label for="search" class="sr-only">Search posts and thought leaders</label>${i('magnifying-glass')}<input id="search" name="q" placeholder="Search for wisdom" autocomplete="off"><kbd>/</kbd></form><button class="mobile-account" data-action="profile" aria-label="Open your account">${avatar('you')}</button><nav class="primary-nav" aria-label="Main navigation">${[['house','Home','home'],['users-three','My Network','network'],['briefcase','Jobs','jobs'],['chat-circle-dots','Messaging','messages'],['bell','Notifications','notifications']].map(([glyph,label,action],k)=>`<button class="nav-item ${k===0?'active':''}" data-action="${action}" ${k===0?'aria-current="page"':''}>${i(glyph,k===0)}${action==='notifications'?'<b class="notification-dot">3</b>':''}<span>${label}</span></button>`).join('')}<button class="nav-item me" data-action="profile">${avatar('you')}<span>Me ${i('caret-down')}</span></button><div class="nav-business"><button class="nav-item" data-action="sponsor">${i('squares-four')}<span>For Business ${i('caret-down')}</span></button><button class="nav-premium" data-action="premium">Try Premium<br>Delusion for £0</button></div></nav></div></header>
 <main class="layout">${leftRail()}<div class="feed-column" id="feed" tabindex="-1"${feed?` data-edition="${e(feed.editionId)}" data-next-cursor="${e(feed.nextCursor||'')}" data-source-name="${e(feed.sourceName||'')}"`:''}>
 <section class="card composer" aria-label="Create a post"><div class="composer-start">${avatar('you')}<button data-action="compose">Start a thought-provoking post</button></div><div class="composer-options">${btn('compose','Media','image','media')}${btn('events','Event','calendar-blank','event')}${btn('compose','Write article','article','article-button')}</div></section>
 <section class="welcome"><h2>Big takes. Little evidence.</h2><p id="feed-status">${e(feed?feed.status:'House edition. Live tech news loads shortly.')}</p></section>
 <div class="feed-controls"><div class="feed-tabs" aria-label="Feed filters"><button class="selected" data-filter="all" aria-pressed="true">For you</button><button data-filter="Tech gospel" aria-pressed="false">Tech gospel</button><button data-filter="The founder life" aria-pressed="false">Founder life</button></div><label class="sort">Sort by: <select aria-label="Sort posts"><option value="top">Top</option><option value="recent">Recent</option></select></label></div>
 <section id="alternate-view" hidden></section><div id="posts">${feedPosts.map(renderPost).join('')}</div><div id="feed-loader" role="status" aria-live="polite" hidden><span class="feed-spinner" aria-hidden="true"></span><span data-feed-loader-text>Loading more questionable insight…</span><button class="button outline" data-action="load-more" hidden>Try again</button></div><div id="empty-state" class="card empty" hidden>${i('magnifying-glass')}<h2>No thought leaders found.</h2><p>Try another search. The takes are out there.</p><button class="button outline" data-action="home">Back to the feed</button></div><div class="feed-end"><strong>You’re all caught up.</strong><p>There’s still time to do some actual work.</p>${btn('home','Back to top','arrow-up','text-button')}</div></div>${rightRail(feed)}</main>
 <div class="page-footer">${renderFooter()}</div>
 <button class="messaging-dock" data-action="messages">${avatar('you')}<strong>Messaging</strong><span class="online-dot" aria-label="Online"></span>${i('dots-three')}${i('pencil-simple')}${i('caret-up')}</button>
 <dialog id="dialog" aria-labelledby="dialog-title"><div class="dialog-header"><h2 id="dialog-title"></h2><button class="icon-button" data-action="close-dialog" aria-label="Close dialog">${i('x')}</button></div><div id="dialog-content"></div></dialog><div id="toast" role="status" aria-live="polite" hidden></div><noscript><div class="noscript">You can read the entire feed without JavaScript. Enable it to post, react and comment.</div></noscript></body></html>`;}
